import {
  createCatalog,
  generateCatalogPrompt,
  type ComponentSchema,
  type ValidationFunction,
} from "@json-render/core";
import { z } from "zod";

/**
 * Component Catalog for AI-Generated Analytics UI
 *
 * This catalog defines all the components that can be generated by AI
 * for TikTok analytics dashboards. Each component has a Zod schema
 * that validates its props, ensuring type-safe generation.
 */

// =============================================================================
// Helper to cast schemas for json-render compatibility
// =============================================================================

/**
 * Helper function to cast Zod schemas to ComponentSchema type
 * This is needed due to Zod 4 type changes
 */
function asProps<T extends z.ZodTypeAny>(schema: T): ComponentSchema {
  return schema as unknown as ComponentSchema;
}

// =============================================================================
// Shared Schemas
// =============================================================================

const alignSchema = z.enum(["start", "center", "end", "stretch"]).optional();
const justifySchema = z
  .enum(["start", "center", "end", "between", "around", "evenly"])
  .optional();
const gapSchema = z.enum(["none", "xs", "sm", "md", "lg", "xl"]).optional();
const trendSchema = z.enum(["up", "down", "neutral"]).optional();

// Chart data point schema - flexible for different chart types
const chartDataPointSchema = z.record(z.string(), z.union([z.string(), z.number()]));

// =============================================================================
// Layout Components
// =============================================================================

const RowSchema = z.object({
  gap: gapSchema.default("md"),
  align: alignSchema.default("center"),
  justify: justifySchema.default("start"),
  wrap: z.boolean().optional().default(false),
});

const ColumnSchema = z.object({
  gap: gapSchema.default("lg"),
  align: alignSchema.default("stretch"),
});

const GridSchema = z.object({
  columns: z.number().min(1).max(12).default(3),
  gap: gapSchema.default("md"),
});

const CardSchema = z.object({
  title: z.string().optional(),
  description: z.string().optional(),
});

// =============================================================================
// Metric Components
// =============================================================================

const MetricCardSchema = z.object({
  label: z.string(),
  value: z.union([z.string(), z.number()]),
  change: z.number().optional(),
  trend: trendSchema,
  format: z.enum(["number", "currency", "percent", "compact"]).optional(),
});

const MetricSchema = z.object({
  label: z.string(),
  value: z.union([z.string(), z.number()]),
  change: z.number().optional(),
  trend: trendSchema,
  format: z.enum(["number", "currency", "percent", "compact"]).optional(),
});

const MetricGroupSchema = z.object({
  metrics: z.array(MetricSchema),
  columns: z.number().min(1).max(6).optional().default(4),
});

// =============================================================================
// Chart Components
// =============================================================================

const BaseChartSchema = z.object({
  data: z.array(chartDataPointSchema),
  title: z.string().optional(),
  height: z.number().optional().default(300),
});

const BarChartSchema = BaseChartSchema.extend({
  xKey: z.string(),
  yKeys: z.array(z.string()).min(1),
  stacked: z.boolean().optional().default(false),
  horizontal: z.boolean().optional().default(false),
});

const LineChartSchema = BaseChartSchema.extend({
  xKey: z.string(),
  yKeys: z.array(z.string()).min(1),
  curved: z.boolean().optional().default(true),
  showDots: z.boolean().optional().default(true),
});

const AreaChartSchema = BaseChartSchema.extend({
  xKey: z.string(),
  yKeys: z.array(z.string()).min(1),
  stacked: z.boolean().optional().default(false),
  gradient: z.boolean().optional().default(true),
});

const PieChartSchema = BaseChartSchema.extend({
  nameKey: z.string(),
  valueKey: z.string(),
  innerRadius: z.number().optional(),
  showLabels: z.boolean().optional().default(true),
});

// =============================================================================
// Table Component
// =============================================================================

const ColumnDefSchema = z.object({
  key: z.string(),
  header: z.string(),
  width: z.string().optional(),
  align: z.enum(["left", "center", "right"]).optional(),
  format: z.enum(["text", "number", "currency", "percent", "date"]).optional(),
});

const DataTableSchema = z.object({
  columns: z.array(ColumnDefSchema).min(1),
  data: z.array(z.record(z.unknown())),
  title: z.string().optional(),
  pageSize: z.number().optional().default(10),
});

// =============================================================================
// TikTok-Specific Components
// =============================================================================

const VideoCardSchema = z.object({
  thumbnailUrl: z.string().url(),
  description: z.string(),
  likes: z.number(),
  comments: z.number(),
  shares: z.number(),
  plays: z.number(),
  postedAt: z.string(),
});

const TopVideosGridSchema = z.object({
  videos: z.array(VideoCardSchema),
  columns: z.number().min(1).max(4).optional().default(3),
});

const EngagementTimelineSchema = z.object({
  data: z.array(
    z.object({
      date: z.string(),
      likes: z.number(),
      comments: z.number(),
      shares: z.number(),
      plays: z.number(),
    })
  ),
  title: z.string().optional(),
  height: z.number().optional().default(300),
});

// =============================================================================
// Text Components
// =============================================================================

const HeadingSchema = z.object({
  text: z.string(),
  level: z.number().min(1).max(6).default(2),
});

const TextSchema = z.object({
  text: z.string(),
  variant: z.enum(["default", "muted", "small"]).optional().default("default"),
});

const BadgeSchema = z.object({
  text: z.string(),
  variant: z
    .enum(["default", "secondary", "destructive", "outline"])
    .optional()
    .default("default"),
});

// =============================================================================
// Validation Functions
// =============================================================================

const validationFunctions: Record<string, ValidationFunction> = {
  isValidDateRange: (value: unknown) => {
    if (typeof value !== "string") return false;
    const date = new Date(value);
    return !isNaN(date.getTime()) && date <= new Date();
  },
  isPositiveNumber: (value: unknown) => {
    return typeof value === "number" && value > 0;
  },
};

// =============================================================================
// Catalog Definition
// =============================================================================

export const catalog = createCatalog({
  components: {
    // Layout Components
    Row: {
      props: asProps(RowSchema),
      hasChildren: true,
      description:
        "Horizontal flex container for laying out elements in a row. Use for toolbars, button groups, or inline elements.",
    },
    Column: {
      props: asProps(ColumnSchema),
      hasChildren: true,
      description:
        "Vertical flex container for stacking elements. Use for forms, card content, or vertical layouts.",
    },
    Grid: {
      props: asProps(GridSchema),
      hasChildren: true,
      description:
        "CSS grid container for multi-column layouts. Use for dashboards, card grids, or gallery layouts.",
    },
    Card: {
      props: asProps(CardSchema),
      hasChildren: true,
      description:
        "Card wrapper with optional title and description. Use to group related content with a visual boundary.",
    },

    // Metric Components
    MetricCard: {
      props: asProps(MetricCardSchema),
      description:
        "Single metric display showing a key value with optional trend indicator. Use for KPIs and important statistics.",
    },
    MetricGroup: {
      props: asProps(MetricGroupSchema),
      description:
        "Group of metrics displayed in a row. Use for showing multiple related KPIs together.",
    },

    // Chart Components
    BarChart: {
      props: asProps(BarChartSchema),
      description:
        "Bar chart for comparing categorical data. Use for showing values across categories or time periods.",
    },
    LineChart: {
      props: asProps(LineChartSchema),
      description:
        "Line chart for showing trends over time. Use for time series data and trend analysis.",
    },
    AreaChart: {
      props: asProps(AreaChartSchema),
      description:
        "Area chart for showing volume over time. Use for cumulative data or emphasizing magnitude.",
    },
    PieChart: {
      props: asProps(PieChartSchema),
      description:
        "Pie chart for showing proportions of a whole. Use for composition analysis and percentage breakdowns.",
    },

    // Table Component
    DataTable: {
      props: asProps(DataTableSchema),
      description:
        "Data table for displaying structured data in rows and columns. Use for lists, records, and detailed data views.",
    },

    // TikTok-Specific Components
    VideoCard: {
      props: asProps(VideoCardSchema),
      description:
        "TikTok video card showing thumbnail and engagement metrics. Use for displaying individual video performance.",
    },
    TopVideosGrid: {
      props: asProps(TopVideosGridSchema),
      description:
        "Grid of top-performing videos. Use for showcasing best content or video galleries.",
    },
    EngagementTimeline: {
      props: asProps(EngagementTimelineSchema),
      description:
        "Timeline chart showing engagement metrics over time. Use for tracking TikTok performance trends.",
    },

    // Text Components
    Heading: {
      props: asProps(HeadingSchema),
      description:
        "Heading text at various levels (h1-h6). Use for section titles and hierarchy.",
    },
    Text: {
      props: asProps(TextSchema),
      description:
        "Text paragraph with styling variants. Use for body text, descriptions, and captions.",
    },
    Badge: {
      props: asProps(BadgeSchema),
      description:
        "Small badge/tag for labels and status indicators. Use for categories, status, or counts.",
    },
  },

  actions: {
    refresh_data: {
      params: asProps(z.object({
        dataSource: z.string().optional(),
      })),
      description: "Refresh the analytics data from the server",
    },
    export_report: {
      params: asProps(z.object({
        format: z.enum(["csv", "pdf", "json"]),
        dateRange: z.string().optional(),
      })),
      description: "Export analytics report in the specified format",
    },
    pin_component: {
      params: asProps(z.object({
        componentId: z.string(),
        position: z.number().optional(),
      })),
      description: "Pin a component to the dashboard for quick access",
    },
    navigate: {
      params: asProps(z.object({
        path: z.string(),
      })),
      description: "Navigate to a different page or section",
    },
  },

  functions: validationFunctions,
});

// =============================================================================
// Catalog Prompt Generation
// =============================================================================

/**
 * Generates the system prompt that describes the component catalog to the AI.
 * This should be included in the AI's system message to enable guardrailed generation.
 */
export function getCatalogPrompt(): string {
  return generateCatalogPrompt(catalog);
}

/**
 * Extended prompt with TikTok analytics context
 */
export function getAnalyticsCatalogPrompt(): string {
  const basePrompt = generateCatalogPrompt(catalog);

  return `${basePrompt}

## Context: TikTok Analytics Dashboard

You are generating UI components for a TikTok analytics dashboard. The data available includes:
- Video performance metrics (plays, likes, comments, shares)
- Account growth data (followers over time)
- Engagement rates and trends
- Top performing content
- Posting patterns and timing analysis

When generating components:
1. ALWAYS wrap your entire response in a Column component to ensure proper vertical spacing between sections
2. Use MetricCard or MetricGroup for key performance indicators
3. Use LineChart or AreaChart for trends over time
4. Use BarChart for comparisons (e.g., video vs video, day vs day)
5. Use PieChart for composition (e.g., engagement breakdown)
6. Use DataTable for detailed video or account lists
7. Use TopVideosGrid for showcasing best performing content
8. Use Card to group related metrics and charts
9. Use Grid for multi-column layouts within a section

Always include meaningful titles and consider the user's analytical needs when selecting components.`;
}

// =============================================================================
// Type Exports
// =============================================================================

export type Catalog = typeof catalog;

// Export individual prop types for component implementations
export type RowProps = z.infer<typeof RowSchema>;
export type ColumnProps = z.infer<typeof ColumnSchema>;
export type GridProps = z.infer<typeof GridSchema>;
export type CardProps = z.infer<typeof CardSchema>;
export type MetricCardProps = z.infer<typeof MetricCardSchema>;
export type MetricGroupProps = z.infer<typeof MetricGroupSchema>;
export type BarChartProps = z.infer<typeof BarChartSchema>;
export type LineChartProps = z.infer<typeof LineChartSchema>;
export type AreaChartProps = z.infer<typeof AreaChartSchema>;
export type PieChartProps = z.infer<typeof PieChartSchema>;
export type DataTableProps = z.infer<typeof DataTableSchema>;
export type VideoCardProps = z.infer<typeof VideoCardSchema>;
export type TopVideosGridProps = z.infer<typeof TopVideosGridSchema>;
export type EngagementTimelineProps = z.infer<typeof EngagementTimelineSchema>;
export type HeadingProps = z.infer<typeof HeadingSchema>;
export type TextProps = z.infer<typeof TextSchema>;
export type BadgeProps = z.infer<typeof BadgeSchema>;
export type ColumnDef = z.infer<typeof ColumnDefSchema>;
