import {
  createCatalog,
  generateCatalogPrompt,
  type ComponentSchema,
  type ValidationFunction,
} from "@json-render/core";
import { z } from "zod";

/**
 * Component Catalog for AI-Generated Analytics UI
 *
 * This catalog defines all the components that can be generated by AI
 * for TikTok analytics dashboards. Each component has a Zod schema
 * that validates its props, ensuring type-safe generation.
 */

// =============================================================================
// Helper to cast schemas for json-render compatibility
// =============================================================================

/**
 * Helper function to cast Zod schemas to ComponentSchema type
 * This is needed due to Zod 4 type changes
 */
function asProps<T extends z.ZodTypeAny>(schema: T): ComponentSchema {
  return schema as unknown as ComponentSchema;
}

// =============================================================================
// Shared Schemas
// =============================================================================

const alignSchema = z.enum(["start", "center", "end", "stretch"]).optional();
const justifySchema = z
  .enum(["start", "center", "end", "between", "around", "evenly"])
  .optional();
const gapSchema = z.enum(["none", "xs", "sm", "md", "lg", "xl"]).optional();
const trendSchema = z.enum(["up", "down", "neutral"]).optional();

// Chart data point schema - flexible for different chart types
const chartDataPointSchema = z.record(z.string(), z.union([z.string(), z.number()]));

// =============================================================================
// Layout Components
// =============================================================================

const RowSchema = z.object({
  gap: gapSchema.default("md"),
  align: alignSchema.default("center"),
  justify: justifySchema.default("start"),
  wrap: z.boolean().optional().default(false),
});

const ColumnSchema = z.object({
  gap: gapSchema.default("lg"),
  align: alignSchema.default("stretch"),
});

const GridSchema = z.object({
  columns: z.number().min(1).max(12).default(3),
  gap: gapSchema.default("md"),
});

const CardSchema = z.object({
  title: z.string().optional(),
  description: z.string().optional(),
});

// =============================================================================
// Metric Components
// =============================================================================

const MetricCardSchema = z.object({
  label: z.string(),
  value: z.union([z.string(), z.number()]),
  change: z.number().optional(),
  trend: trendSchema,
  format: z.enum(["number", "currency", "percent", "compact"]).optional(),
});

const MetricGroupSchema = z.object({
  metrics: z.array(MetricCardSchema),
  columns: z.number().min(1).max(6).optional().default(4),
});

// =============================================================================
// Chart Components
// =============================================================================

const BaseChartSchema = z.object({
  data: z.array(chartDataPointSchema),
  title: z.string().optional(),
  height: z.number().optional().default(300),
});

const BarChartSchema = BaseChartSchema.extend({
  xKey: z.string(),
  yKeys: z.array(z.string()).min(1),
  stacked: z.boolean().optional().default(false),
  horizontal: z.boolean().optional().default(false),
});

const LineChartSchema = BaseChartSchema.extend({
  xKey: z.string(),
  yKeys: z.array(z.string()).min(1),
  curved: z.boolean().optional().default(true),
  showDots: z.boolean().optional().default(true),
});

const AreaChartSchema = BaseChartSchema.extend({
  xKey: z.string(),
  yKeys: z.array(z.string()).min(1),
  stacked: z.boolean().optional().default(false),
  gradient: z.boolean().optional().default(true),
});

const PieChartSchema = BaseChartSchema.extend({
  nameKey: z.string(),
  valueKey: z.string(),
  innerRadius: z.number().optional(),
  showLabels: z.boolean().optional().default(true),
});

// =============================================================================
// Table Component
// =============================================================================

const ColumnDefSchema = z.object({
  key: z.string(),
  header: z.string(),
  width: z.string().optional(),
  align: z.enum(["left", "center", "right"]).optional(),
  format: z.enum(["text", "number", "currency", "percent", "date"]).optional(),
});

const DataTableSchema = z.object({
  columns: z.array(ColumnDefSchema).min(1),
  data: z.array(z.record(z.unknown())),
  title: z.string().optional(),
  pageSize: z.number().optional().default(10),
});

// =============================================================================
// TikTok-Specific Components
// =============================================================================

const VideoCardSchema = z.object({
  thumbnailUrl: z.string().url(),
  description: z.string(),
  likes: z.number(),
  comments: z.number(),
  shares: z.number(),
  plays: z.number(),
  postedAt: z.string(),
  videoUrl: z.string().url().optional(),
  tiktokId: z.string().optional(),
});

const TopVideosGridSchema = z.object({
  videos: z.array(VideoCardSchema),
  columns: z.number().min(1).max(4).optional().default(3),
});

const EngagementTimelineSchema = z.object({
  data: z.array(
    z.object({
      date: z.string(),
      likes: z.number(),
      comments: z.number(),
      shares: z.number(),
      plays: z.number(),
    })
  ),
  title: z.string().optional(),
  height: z.number().optional().default(300),
});

// =============================================================================
// Text Components
// =============================================================================

const HeadingSchema = z.object({
  text: z.string(),
  level: z.number().min(1).max(6).default(2),
});

const TextSchema = z.object({
  text: z.string(),
  variant: z.enum(["default", "muted", "small"]).optional().default("default"),
});

const BadgeSchema = z.object({
  text: z.string(),
  variant: z
    .enum(["default", "secondary", "destructive", "outline"])
    .optional()
    .default("default"),
});

// =============================================================================
// Alert / Feedback Components
// =============================================================================

const AlertSchema = z.object({
  variant: z.enum(["default", "destructive"]).optional().default("default"),
  title: z.string().optional(),
  description: z.string(),
});

const ProgressSchema = z.object({
  value: z.number().min(0).max(100),
  label: z.string().optional(),
});

const SeparatorSchema = z.object({
  orientation: z
    .enum(["horizontal", "vertical"])
    .optional()
    .default("horizontal"),
});

const AvatarSchema = z.object({
  src: z.string().url().optional(),
  fallback: z.string().max(2),
  size: z.enum(["sm", "default", "lg"]).optional().default("default"),
});

const SkeletonSchema = z.object({
  width: z.string().optional(),
  height: z.string().optional(),
  rounded: z
    .enum(["none", "sm", "md", "lg", "full"])
    .optional()
    .default("md"),
});

// =============================================================================
// Container / Wrapper Components
// =============================================================================

const TooltipSchema = z.object({
  content: z.string(),
});

const HoverCardSchema = z.object({
  title: z.string().optional(),
  description: z.string().optional(),
  image: z.string().url().optional(),
});

const ScrollAreaSchema = z.object({
  maxHeight: z.string().optional().default("400px"),
});

const AspectRatioSchema = z.object({
  ratio: z.number().optional().default(16 / 9),
});

// =============================================================================
// Compositional Components
// =============================================================================

const AccordionItemSchema = z.object({
  title: z.string(),
  value: z.string().optional(),
});

const AccordionSchema = z.object({
  items: z.array(AccordionItemSchema).min(1),
  type: z.enum(["single", "multiple"]).optional().default("single"),
  defaultValue: z.array(z.string()).optional(),
});

const TabItemSchema = z.object({
  label: z.string(),
  value: z.string(),
});

const TabsSchema = z.object({
  tabs: z.array(TabItemSchema).min(1),
  defaultTab: z.string().optional(),
});

const CollapsibleSchema = z.object({
  title: z.string(),
  defaultOpen: z.boolean().optional().default(false),
});

// =============================================================================
// Validation Functions
// =============================================================================

const validationFunctions: Record<string, ValidationFunction> = {
  isValidDateRange: (value: unknown) => {
    if (typeof value !== "string") return false;
    const date = new Date(value);
    return !isNaN(date.getTime()) && date <= new Date();
  },
  isPositiveNumber: (value: unknown) => {
    return typeof value === "number" && value > 0;
  },
};

// =============================================================================
// Catalog Definition
// =============================================================================

export const catalog = createCatalog({
  components: {
    // Layout Components
    Row: {
      props: asProps(RowSchema),
      hasChildren: true,
      description:
        "Horizontal flex container for laying out elements in a row. Use for toolbars, button groups, or inline elements.",
    },
    Column: {
      props: asProps(ColumnSchema),
      hasChildren: true,
      description:
        "Vertical flex container for stacking elements. Use for forms, card content, or vertical layouts.",
    },
    Grid: {
      props: asProps(GridSchema),
      hasChildren: true,
      description:
        "CSS grid container for multi-column layouts. Use for dashboards, card grids, or gallery layouts.",
    },
    Card: {
      props: asProps(CardSchema),
      hasChildren: true,
      description:
        "Card wrapper with optional title and description. Use to group related content with a visual boundary.",
    },

    // Metric Components
    MetricCard: {
      props: asProps(MetricCardSchema),
      description:
        "Single metric display showing a key value with optional trend indicator. Use for KPIs and important statistics.",
    },
    MetricGroup: {
      props: asProps(MetricGroupSchema),
      description:
        "Group of metrics displayed in a row. Use for showing multiple related KPIs together.",
    },

    // Chart Components
    BarChart: {
      props: asProps(BarChartSchema),
      description:
        "Bar chart for comparing categorical data. Use for showing values across categories or time periods.",
    },
    LineChart: {
      props: asProps(LineChartSchema),
      description:
        "Line chart for showing trends over time. Use for time series data and trend analysis.",
    },
    AreaChart: {
      props: asProps(AreaChartSchema),
      description:
        "Area chart for showing volume over time. Use for cumulative data or emphasizing magnitude.",
    },
    PieChart: {
      props: asProps(PieChartSchema),
      description:
        "Pie chart for showing proportions of a whole. Use for composition analysis and percentage breakdowns.",
    },

    // Table Component
    DataTable: {
      props: asProps(DataTableSchema),
      description:
        "Data table for displaying structured data in rows and columns. Use for lists, records, and detailed data views.",
    },

    // TikTok-Specific Components
    VideoCard: {
      props: asProps(VideoCardSchema),
      description:
        "TikTok video card showing thumbnail and engagement metrics. Clicking opens an embedded video player. Include videoUrl for full embed functionality.",
    },
    TopVideosGrid: {
      props: asProps(TopVideosGridSchema),
      description:
        "Grid of top-performing videos. Use for showcasing best content or video galleries.",
    },
    EngagementTimeline: {
      props: asProps(EngagementTimelineSchema),
      description:
        "Timeline chart showing engagement metrics over time. Use for tracking TikTok performance trends.",
    },

    // Text Components
    Heading: {
      props: asProps(HeadingSchema),
      description:
        "Heading text at various levels (h1-h6). Use for section titles and hierarchy.",
    },
    Text: {
      props: asProps(TextSchema),
      description:
        "Text paragraph with styling variants. Use for body text, descriptions, and captions.",
    },
    Badge: {
      props: asProps(BadgeSchema),
      description:
        "Small badge/tag for labels and status indicators. Use for categories, status, or counts.",
    },

    // Alert / Feedback Components
    Alert: {
      props: asProps(AlertSchema),
      description:
        "Alert banner for important messages, warnings, or errors. Use 'destructive' variant for critical warnings, 'default' for informational callouts, tips, and milestones.",
    },
    Progress: {
      props: asProps(ProgressSchema),
      description:
        "Progress bar showing completion percentage (0-100). Use for goal progress, benchmarks vs targets, or any metric as a percentage of a target.",
    },
    Separator: {
      props: asProps(SeparatorSchema),
      description:
        "Visual divider line between sections. Default is horizontal. Use vertical within Row layouts.",
    },
    Avatar: {
      props: asProps(AvatarSchema),
      description:
        "User or account avatar showing an image with fallback initials. Use for TikTok profile pictures or commenter avatars.",
    },
    Skeleton: {
      props: asProps(SkeletonSchema),
      description:
        "Loading placeholder with animated pulse effect. Set width/height for desired shape.",
    },

    // Container / Wrapper Components
    Tooltip: {
      props: asProps(TooltipSchema),
      hasChildren: true,
      description:
        "Hover tooltip showing text when user hovers over the child element. Use to add context to metrics, abbreviations, or labels.",
    },
    HoverCard: {
      props: asProps(HoverCardSchema),
      hasChildren: true,
      description:
        "Rich hover card showing preview popup with title, description, and optional image. Use for user profiles, video previews, or detailed metric explanations.",
    },
    ScrollArea: {
      props: asProps(ScrollAreaSchema),
      hasChildren: true,
      description:
        "Scrollable container with custom scrollbar. Constrains content to a max height. Use for long lists, large tables, or content needing vertical bounds.",
    },
    AspectRatio: {
      props: asProps(AspectRatioSchema),
      hasChildren: true,
      description:
        "Container maintaining a fixed aspect ratio. Use 16/9 for landscape video, 9/16 for TikTok portrait content, 1 for square images.",
    },

    // Compositional Components
    Accordion: {
      props: asProps(AccordionSchema),
      hasChildren: true,
      description:
        "Expandable accordion with multiple titled sections. Each child maps by index to the corresponding item. Use for FAQs, detailed breakdowns, or grouped sections. Set type 'multiple' to allow expanding several sections simultaneously.",
    },
    Tabs: {
      props: asProps(TabsSchema),
      hasChildren: true,
      description:
        "Tabbed interface with labeled panels. Each child maps by index to the corresponding tab. Use for different views of the same data, time period comparisons, or categorized content.",
    },
    Collapsible: {
      props: asProps(CollapsibleSchema),
      hasChildren: true,
      description:
        "Single expandable/collapsible section with a title toggle. Use for 'show more' patterns, optional detail sections, or secondary information hidden by default.",
    },
  },

  actions: {
    refresh_data: {
      params: asProps(z.object({
        dataSource: z.string().optional(),
      })),
      description: "Refresh the analytics data from the server",
    },
    export_report: {
      params: asProps(z.object({
        format: z.enum(["csv", "pdf", "json"]),
        dateRange: z.string().optional(),
      })),
      description: "Export analytics report in the specified format",
    },
    pin_component: {
      params: asProps(z.object({
        componentId: z.string(),
        position: z.number().optional(),
      })),
      description: "Pin a component to the dashboard for quick access",
    },
    navigate: {
      params: asProps(z.object({
        path: z.string(),
      })),
      description: "Navigate to a different page or section",
    },
  },

  functions: validationFunctions,
});

// =============================================================================
// Catalog Prompt Generation
// =============================================================================

/**
 * Generates the system prompt that describes the component catalog to the AI.
 * This should be included in the AI's system message to enable guardrailed generation.
 */
export function getCatalogPrompt(): string {
  return generateCatalogPrompt(catalog);
}

/**
 * Extended prompt with TikTok analytics context.
 * Strips auto-generated sections that are irrelevant to the chat context
 * (Actions, Visibility Conditions, Validation Functions) to save tokens.
 */
export function getAnalyticsCatalogPrompt(): string {
  let prompt = generateCatalogPrompt(catalog);

  // Remove sections that don't apply to the analytics chat
  prompt = prompt.replace(/## Available Actions[\s\S]*?(?=## |$)/, "");
  prompt = prompt.replace(/## Visibility Conditions[\s\S]*?(?=## |$)/, "");
  prompt = prompt.replace(/## Validation Functions[\s\S]*?(?=## |$)/, "");

  return `${prompt}
## Context: TikTok Analytics Dashboard

You are generating UI components for a TikTok analytics dashboard. The data available includes:
- Video performance metrics (plays, likes, comments, shares)
- Account growth data (followers over time)
- Engagement rates and trends
- Top performing content
- Posting patterns and timing analysis

When generating components:
1. ALWAYS wrap your entire response in a Column component to ensure proper vertical spacing
2. Use MetricCard or MetricGroup for key performance indicators
3. Use LineChart or AreaChart for trends over time
4. Use BarChart for comparisons (e.g., video vs video, day vs day)
5. Use PieChart for composition (e.g., engagement breakdown)
6. Use DataTable for detailed video or account lists
7. Use TopVideosGrid for showcasing best performing content
8. Use Card to group related metrics and charts
9. Use Grid for multi-column layouts within a section
10. Use the remaining components (Alert, Progress, Separator, Tabs, Accordion, Collapsible, Avatar, Tooltip, ScrollArea, AspectRatio, Skeleton, HoverCard) as appropriate per their descriptions above

### Compositional components (Accordion, Tabs, Collapsible):
- For Accordion and Tabs, the children array maps BY INDEX to the items/tabs array
- Ensure the children array length matches the items/tabs array length

Always include meaningful titles and consider the user's analytical needs when selecting components.`;
}

// =============================================================================
// Type Exports
// =============================================================================

export type Catalog = typeof catalog;

// Export individual prop types for component implementations
export type RowProps = z.infer<typeof RowSchema>;
export type ColumnProps = z.infer<typeof ColumnSchema>;
export type GridProps = z.infer<typeof GridSchema>;
export type CardProps = z.infer<typeof CardSchema>;
export type MetricCardProps = z.infer<typeof MetricCardSchema>;
export type MetricGroupProps = z.infer<typeof MetricGroupSchema>;
export type BarChartProps = z.infer<typeof BarChartSchema>;
export type LineChartProps = z.infer<typeof LineChartSchema>;
export type AreaChartProps = z.infer<typeof AreaChartSchema>;
export type PieChartProps = z.infer<typeof PieChartSchema>;
export type DataTableProps = z.infer<typeof DataTableSchema>;
export type VideoCardProps = z.infer<typeof VideoCardSchema>;
export type TopVideosGridProps = z.infer<typeof TopVideosGridSchema>;
export type EngagementTimelineProps = z.infer<typeof EngagementTimelineSchema>;
export type HeadingProps = z.infer<typeof HeadingSchema>;
export type TextProps = z.infer<typeof TextSchema>;
export type BadgeProps = z.infer<typeof BadgeSchema>;
export type AlertProps = z.infer<typeof AlertSchema>;
export type ProgressProps = z.infer<typeof ProgressSchema>;
export type SeparatorProps = z.infer<typeof SeparatorSchema>;
export type AvatarProps = z.infer<typeof AvatarSchema>;
export type SkeletonProps = z.infer<typeof SkeletonSchema>;
export type TooltipProps = z.infer<typeof TooltipSchema>;
export type HoverCardProps = z.infer<typeof HoverCardSchema>;
export type ScrollAreaProps = z.infer<typeof ScrollAreaSchema>;
export type AspectRatioProps = z.infer<typeof AspectRatioSchema>;
export type AccordionProps = z.infer<typeof AccordionSchema>;
export type TabsProps = z.infer<typeof TabsSchema>;
export type CollapsibleProps = z.infer<typeof CollapsibleSchema>;
export type ColumnDef = z.infer<typeof ColumnDefSchema>;
