"use client";

import { standardComponents } from "@json-render/remotion";
import {
  BarChartClip,
  LineChartClip,
  AreaChartClip,
  PieChartClip,
  EngagementTimelineClip,
  MetricCardClip,
  DataTableClip,
  VideoCardClip,
  BadgeClip,
  ProgressClip,
  AlertClip,
  AvatarClip,
  CodeBlockClip,
  CardGridClip,
  ChecklistClip,
  CountUpClip,
  ComparisonClip,
  RankingClip,
  CalloutClip,
  AnimatedListClip,
  TypingTextClip,
  TitleCardClip,
  StatCardClip,
  QuoteCardClip,
  SplitScreenClip,
  LowerThirdClip,
  TextOverlayClip,
} from "@/components/remotion/clips";

export const videoRegistry = {
  ...standardComponents,
  BarChart: BarChartClip,
  LineChart: LineChartClip,
  AreaChart: AreaChartClip,
  PieChart: PieChartClip,
  EngagementTimeline: EngagementTimelineClip,
  MetricCard: MetricCardClip,
  DataTable: DataTableClip,
  VideoCard: VideoCardClip,
  Badge: BadgeClip,
  Progress: ProgressClip,
  Alert: AlertClip,
  Avatar: AvatarClip,
  CodeBlock: CodeBlockClip,
  CardGrid: CardGridClip,
  Checklist: ChecklistClip,
  CountUp: CountUpClip,
  Comparison: ComparisonClip,
  Ranking: RankingClip,
  Callout: CalloutClip,
  AnimatedList: AnimatedListClip,
  TypingText: TypingTextClip,
  TitleCard: TitleCardClip,
  StatCard: StatCardClip,
  QuoteCard: QuoteCardClip,
  SplitScreen: SplitScreenClip,
  LowerThird: LowerThirdClip,
  TextOverlay: TextOverlayClip,
};
