'use client';

import { useChat, type UIMessage } from '@ai-sdk/react';
import { DefaultChatTransport } from 'ai';
import { useMemo, useCallback, useEffect, useRef, useState } from 'react';
import { useCredits } from '@/hooks/use-credits';

/**
 * Represents a UI component tree structure for rendering analytics visualizations.
 * This is the output format of the generateUI tool.
 */
export interface UITree {
  component: string;
  props: Record<string, unknown>;
  children?: UITree[];
}

/**
 * Represents analytics data fetched from the fetchAnalyticsData tool.
 */
export interface AnalyticsData {
  type: string;
  data: unknown;
}

/**
 * Tool invocation part extracted from messages.
 * In AI SDK v6, tool parts are typed as `tool-{toolName}`.
 */
interface ToolPart {
  type: string;
  toolCallId: string;
  state: 'input-streaming' | 'input-available' | 'output-available' | 'output-error';
  input?: unknown;
  output?: unknown;
  errorText?: string;
}

/**
 * Extract tool parts from a UIMessage.
 * Tool parts have types like 'tool-generateUI' or 'tool-fetchAnalyticsData'.
 */
function extractToolParts(message: UIMessage): ToolPart[] {
  const toolParts: ToolPart[] = [];

  for (const part of message.parts) {
    // Check if this is a tool part (type starts with 'tool-')
    if (typeof part.type === 'string' && part.type.startsWith('tool-')) {
      toolParts.push(part as unknown as ToolPart);
    }
  }

  return toolParts;
}

/**
 * Represents a video timeline spec generated by the generateVideo tool.
 */
export interface VideoSpec {
  composition: {
    id: string;
    fps: number;
    width: number;
    height: number;
    durationInFrames: number;
  };
  tracks: { id: string; name: string; type: string; enabled: boolean }[];
  clips: {
    id: string;
    trackId: string;
    component: string;
    props: Record<string, unknown>;
    from: number;
    durationInFrames: number;
  }[];
  audio: { tracks: unknown[] };
}

/**
 * Represents a diagram result from the createDiagram tool.
 */
export interface DiagramResult {
  title: string;
  elements: unknown[];
}

/**
 * Options for configuring the useAnalyticsChat hook.
 */
export interface UseAnalyticsChatOptions {
  /**
   * The currently selected account ID. When this changes, the chat resets
   * so the AI assistant starts fresh with the new account context.
   */
  selectedAccountId?: number | null;

  /**
   * Callback fired when new UI trees (visualizations) are generated by the AI.
   * This is called whenever the uiTrees array changes and contains new trees.
   */
  onVisualizationGenerated?: (trees: UITree[]) => void;

  /**
   * Callback fired when a new diagram is generated by the AI.
   */
  onDiagramGenerated?: (diagram: DiagramResult) => void;
}

/**
 * Custom hook for managing the analytics chat interface.
 * Wraps the AI SDK's useChat hook and provides convenient accessors
 * for extracted UI trees and analytics data from tool invocations.
 */
export function useAnalyticsChat(options?: UseAnalyticsChatOptions) {
  const { selectedAccountId, onVisualizationGenerated, onDiagramGenerated } = options || {};
  const [insufficientCredits, setInsufficientCredits] = useState(false);
  const { refresh: refreshCredits } = useCredits();
  const prevAccountIdRef = useRef<number | null | undefined>(selectedAccountId);
  // Recreate transport when selectedAccountId changes so the body stays in sync
  const transport = useMemo(
    () =>
      new DefaultChatTransport({
        api: '/api/chat',
        prepareSendMessagesRequest: ({ id, messages }) => ({
          body: {
            id,
            messages,
            selectedAccountId: selectedAccountId ?? undefined,
          },
        }),
      }),
    [selectedAccountId]
  );

  const {
    id,
    messages,
    status,
    error,
    sendMessage,
    stop,
    setMessages,
    regenerate,
  } = useChat({
    transport,
    onFinish: () => {
      // Refresh credit/token balance after AI response completes
      refreshCredits();
    },
    onError: (error) => {
      if (error.message?.includes('402') || (error as { status?: number }).status === 402) {
        setInsufficientCredits(true);
      }
    },
  });

  // Reset chat when the selected account changes
  useEffect(() => {
    if (prevAccountIdRef.current !== undefined && prevAccountIdRef.current !== selectedAccountId && messages.length > 0) {
      setMessages([]);
    }
    prevAccountIdRef.current = selectedAccountId;
  }, [selectedAccountId, messages.length, setMessages]);

  /**
   * Extract UI trees from generateUI tool call results in messages.
   * Only includes tool calls that have completed with output.
   */
  const uiTrees = useMemo(() => {
    const trees: UITree[] = [];

    for (const message of messages) {
      if (message.role === 'assistant') {
        const toolParts = extractToolParts(message);

        for (const toolPart of toolParts) {
          // Check if this is a generateUI tool with output
          if (
            toolPart.type === 'tool-generateUI' &&
            toolPart.state === 'output-available' &&
            toolPart.output
          ) {
            trees.push(toolPart.output as UITree);
          }
        }
      }
    }

    return trees;
  }, [messages]);

  /**
   * Extract analytics data from fetchAnalyticsData tool call results in messages.
   * Only includes tool calls that have completed with output.
   */
  const analyticsData = useMemo(() => {
    const data: AnalyticsData[] = [];

    for (const message of messages) {
      if (message.role === 'assistant') {
        const toolParts = extractToolParts(message);

        for (const toolPart of toolParts) {
          // Check if this is a fetchAnalyticsData tool with output
          if (
            toolPart.type === 'tool-fetchAnalyticsData' &&
            toolPart.state === 'output-available' &&
            toolPart.output
          ) {
            // Extract the query type from input if available
            const input = toolPart.input as { query?: string } | undefined;
            data.push({
              type: input?.query || 'unknown',
              data: toolPart.output,
            });
          }
        }
      }
    }

    return data;
  }, [messages]);

  /**
   * Extract video specs from generateVideo tool call results in messages.
   */
  const videoSpecs = useMemo(() => {
    const specs: VideoSpec[] = [];

    for (const message of messages) {
      if (message.role === 'assistant') {
        const toolParts = extractToolParts(message);

        for (const toolPart of toolParts) {
          if (
            toolPart.type === 'tool-generateVideo' &&
            toolPart.state === 'output-available' &&
            toolPart.output
          ) {
            specs.push(toolPart.output as VideoSpec);
          }
        }
      }
    }

    return specs;
  }, [messages]);

  /**
   * Extract diagram results from createDiagram tool call results in messages.
   */
  const diagramResults = useMemo(() => {
    const diagrams: DiagramResult[] = [];

    for (const message of messages) {
      if (message.role === 'assistant') {
        const toolParts = extractToolParts(message);

        for (const toolPart of toolParts) {
          if (
            toolPart.type === 'tool-createDiagram' &&
            toolPart.state === 'output-available' &&
            toolPart.output
          ) {
            const output = toolPart.output as { title?: string; elements?: unknown[]; error?: string };
            if (output.elements && Array.isArray(output.elements)) {
              diagrams.push({
                title: output.title || 'Diagram',
                elements: output.elements,
              });
            }
          }
        }
      }
    }

    return diagrams;
  }, [messages]);

  /**
   * Get the latest UI tree (most recent visualization).
   */
  const latestUITree = useMemo(() => {
    return uiTrees[uiTrees.length - 1] || null;
  }, [uiTrees]);

  /**
   * Get the latest analytics data.
   */
  const latestData = useMemo(() => {
    return analyticsData[analyticsData.length - 1] || null;
  }, [analyticsData]);

  /**
   * Track the previous UI trees count to detect when new trees are added.
   */
  const prevTreesCountRef = useRef(0);

  /**
   * Track the previous diagram count to detect when new diagrams are added.
   */
  const prevDiagramsCountRef = useRef(0);

  /**
   * Fire the onVisualizationGenerated callback when new UI trees are added.
   */
  useEffect(() => {
    const currentCount = uiTrees.length;
    const prevCount = prevTreesCountRef.current;

    if (currentCount > prevCount && onVisualizationGenerated) {
      const newTrees = uiTrees.slice(prevCount);
      onVisualizationGenerated(newTrees);
    }

    prevTreesCountRef.current = currentCount;
  }, [uiTrees, onVisualizationGenerated]);

  /**
   * Fire the onDiagramGenerated callback when new diagrams are added.
   */
  useEffect(() => {
    const currentCount = diagramResults.length;
    const prevCount = prevDiagramsCountRef.current;

    if (currentCount > prevCount && onDiagramGenerated) {
      const newDiagrams = diagramResults.slice(prevCount);
      for (const diagram of newDiagrams) {
        onDiagramGenerated(diagram);
      }
    }

    prevDiagramsCountRef.current = currentCount;
  }, [diagramResults, onDiagramGenerated]);

  /**
   * Check if the chat is currently generating/streaming a response.
   */
  const isGenerating = useMemo(() => {
    return status === 'streaming' || status === 'submitted';
  }, [status]);

  /**
   * Check if the chat is in a loading state (submitted but not yet streaming).
   */
  const isLoading = useMemo(() => {
    return status === 'submitted';
  }, [status]);

  /**
   * Check if there are any pending tool calls (tools with input but no output yet).
   */
  const hasPendingToolCalls = useMemo(() => {
    for (const message of messages) {
      if (message.role === 'assistant') {
        const toolParts = extractToolParts(message);

        for (const toolPart of toolParts) {
          if (
            toolPart.state === 'input-streaming' ||
            toolPart.state === 'input-available'
          ) {
            return true;
          }
        }
      }
    }
    return false;
  }, [messages]);

  /**
   * Clear the chat history and reset state.
   */
  const clearChat = useCallback(() => {
    setMessages([]);
  }, [setMessages]);

  /**
   * Submit a message to the chat.
   * This is a convenience wrapper around sendMessage.
   */
  const submitMessage = useCallback(
    async (text: string) => {
      if (!text.trim()) return;
      await sendMessage({ text });
    },
    [sendMessage]
  );

  /**
   * Get all text content from messages (excluding tool parts).
   * Useful for displaying message history without tool invocation details.
   */
  const getMessageText = useCallback((message: UIMessage): string => {
    const textParts: string[] = [];

    for (const part of message.parts) {
      if (part.type === 'text') {
        textParts.push((part as { type: 'text'; text: string }).text);
      }
    }

    return textParts.join('\n');
  }, []);

  return {
    // Chat identification
    id,

    // Message state
    messages,

    // Status information
    status,
    isLoading,
    isGenerating,
    hasPendingToolCalls,
    error,
    insufficientCredits,

    // Actions
    sendMessage,
    submitMessage,
    stop,
    clearChat,
    setMessages,
    regenerate,

    // Extracted data
    uiTrees,
    videoSpecs,
    analyticsData,
    diagramResults,
    latestUITree,
    latestData,

    // Utilities
    getMessageText,
  };
}

/**
 * Type for the return value of useAnalyticsChat.
 * Useful for typing components that receive the hook's return value as props.
 */
export type UseAnalyticsChatReturn = ReturnType<typeof useAnalyticsChat>;
