'use client';

import { useChat, type UIMessage } from '@ai-sdk/react';
import { DefaultChatTransport, isToolUIPart } from 'ai';
import { useMemo, useCallback, useEffect, useRef, useState, type MutableRefObject } from 'react';
import { useCredits } from '@/hooks/use-credits';
import type { DiagramResult } from '@/lib/ai-tools/chat-tools';

export type { DiagramResult };

/**
 * Options for configuring the useAnalyticsChat hook.
 */
export interface UseAnalyticsChatOptions {
  /**
   * The currently selected account IDs. When this set changes, the chat resets
   * so the AI assistant starts fresh with the new account context.
   */
  selectedAccountIds?: number[];

  /**
   * Callback fired when a new diagram is generated by the AI.
   */
  onDiagramGenerated?: (diagram: DiagramResult) => void;
}

/**
 * Custom hook for managing the analytics chat interface.
 * Wraps the AI SDK's useChat hook and provides convenient accessors
 * for extracted UI trees and diagram results from tool invocations.
 */
export function useAnalyticsChat(options?: UseAnalyticsChatOptions) {
  const { selectedAccountIds, onDiagramGenerated } = options || {};
  const [insufficientCredits, setInsufficientCredits] = useState(false);
  const { refresh: refreshCredits } = useCredits();
  const pollTimersRef: MutableRefObject<ReturnType<typeof setTimeout>[]> = useRef([]);
  // Serialize the account IDs array for stable comparison
  const accountIdsKey = selectedAccountIds?.slice().sort().join(',') ?? '';
  const prevAccountIdsKeyRef = useRef(accountIdsKey);
  // Recreate transport when selectedAccountIds changes so the body stays in sync
  const transport = useMemo(
    () =>
      new DefaultChatTransport({
        api: '/api/chat',
        prepareSendMessagesRequest: ({ id, messages }) => ({
          body: {
            id,
            messages,
            selectedAccountIds: selectedAccountIds?.length ? selectedAccountIds : undefined,
          },
        }),
      }),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [accountIdsKey]
  );

  const {
    id,
    messages,
    status,
    error,
    sendMessage,
    stop,
    setMessages,
    regenerate,
  } = useChat({
    transport,
    onFinish: () => {
      // Polar meter balances are eventually consistent — the server-side
      // onFinish ingests the token event *after* the stream is sent, so a
      // single immediate refresh almost always reads the stale balance.
      // Poll a few times at short intervals to catch the update.
      pollTimersRef.current.forEach(clearTimeout);
      pollTimersRef.current = [1_000, 3_000, 6_000].map((delay) =>
        setTimeout(() => refreshCredits(), delay)
      );
    },
    onError: (error) => {
      if (error.message?.includes('402') || (error as { status?: number }).status === 402) {
        setInsufficientCredits(true);
      }
    },
  });

  // Clean up poll timers on unmount
  useEffect(() => {
    const timers = pollTimersRef;
    return () => timers.current.forEach(clearTimeout);
  }, []);

  // Reset chat when the selected accounts change
  useEffect(() => {
    if (prevAccountIdsKeyRef.current !== accountIdsKey && messages.length > 0) {
      setMessages([]);
    }
    prevAccountIdsKeyRef.current = accountIdsKey;
  }, [accountIdsKey, messages.length, setMessages]);

  /**
   * Extract diagram results from createDiagram tool call results in messages.
   */
  const diagramResults = useMemo(() => {
    const diagrams: DiagramResult[] = [];

    for (const message of messages) {
      if (message.role === 'assistant') {
        for (const part of message.parts) {
          if (
            isToolUIPart(part) &&
            part.type === 'tool-createDiagram' &&
            part.state === 'output-available' &&
            part.output
          ) {
            const output = part.output as { title?: string; elements?: unknown[]; error?: string };
            if (output.elements && Array.isArray(output.elements)) {
              diagrams.push({
                title: output.title || 'Diagram',
                elements: output.elements,
              });
            }
          }
        }
      }
    }

    return diagrams;
  }, [messages]);

  /**
   * Track the previous diagram count to detect when new diagrams are added.
   */
  const prevDiagramsCountRef = useRef(0);

  /**
   * Fire the onDiagramGenerated callback when new diagrams are added.
   */
  useEffect(() => {
    const currentCount = diagramResults.length;
    const prevCount = prevDiagramsCountRef.current;

    if (currentCount > prevCount && onDiagramGenerated) {
      const newDiagrams = diagramResults.slice(prevCount);
      for (const diagram of newDiagrams) {
        onDiagramGenerated(diagram);
      }
    }

    prevDiagramsCountRef.current = currentCount;
  }, [diagramResults, onDiagramGenerated]);

  /**
   * Check if the chat is currently generating/streaming a response.
   */
  const isGenerating = useMemo(() => {
    return status === 'streaming' || status === 'submitted';
  }, [status]);

  /**
   * Check if the chat is in a loading state (submitted but not yet streaming).
   */
  const isLoading = useMemo(() => {
    return status === 'submitted';
  }, [status]);

  /**
   * Check if there are any pending tool calls (tools with input but no output yet).
   */
  const hasPendingToolCalls = useMemo(() => {
    for (const message of messages) {
      if (message.role === 'assistant') {
        for (const part of message.parts) {
          if (
            isToolUIPart(part) &&
            (part.state === 'input-streaming' || part.state === 'input-available')
          ) {
            return true;
          }
        }
      }
    }
    return false;
  }, [messages]);

  /**
   * Clear the chat history and reset state.
   */
  const clearChat = useCallback(() => {
    setMessages([]);
  }, [setMessages]);

  /**
   * Submit a message to the chat.
   * This is a convenience wrapper around sendMessage.
   */
  const submitMessage = useCallback(
    async (text: string) => {
      if (!text.trim()) return;
      await sendMessage({ text });
    },
    [sendMessage]
  );

  /**
   * Get all text content from messages (excluding tool parts).
   * Useful for displaying message history without tool invocation details.
   */
  const getMessageText = useCallback((message: UIMessage): string => {
    const textParts: string[] = [];

    for (const part of message.parts) {
      if (part.type === 'text') {
        textParts.push((part as { type: 'text'; text: string }).text);
      }
    }

    return textParts.join('\n');
  }, []);

  return {
    // Chat identification
    id,

    // Message state
    messages,

    // Status information
    status,
    isLoading,
    isGenerating,
    hasPendingToolCalls,
    error,
    insufficientCredits,

    // Actions
    sendMessage,
    submitMessage,
    stop,
    clearChat,
    setMessages,
    regenerate,

    // Extracted data
    diagramResults,

    // Utilities
    getMessageText,
  };
}

/**
 * Type for the return value of useAnalyticsChat.
 * Useful for typing components that receive the hook's return value as props.
 */
export type UseAnalyticsChatReturn = ReturnType<typeof useAnalyticsChat>;
